
FROM node:22-slim

RUN apt-get update && \
    apt-get install -y sqlite3 libsqlite3-dev build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ../../package*.json ./

COPY ./api/songbook.db .

RUN npm install

COPY . .

RUN chmod 666 ./api/songbook.db

EXPOSE 3001

CMD [ "node", "api/server.ts" ]