networks:
    lyrk-stack-network:

services:
    playwright:
        network_mode: ${NETWORK_MODE}
        build:
            dockerfile: ./docker/test/dockerfile
        volumes:
            - ./playwright-report:/app/playwright-report
            - ./test-results:/app/test-results
        environment:
            - VITE_CLIENT_BASE_URL=${VITE_CLIENT_BASE_URL}
    lyrk-stack-frontend:
        networks:
            - lyrk-stack-network
        build:
            dockerfile: ./docker/frontend/dockerfile
        environment:
            - VITE_CLIENT_BASE_URL=${VITE_CLIENT_BASE_URL}
            - VITE_SERVER_BASE_URL=${VITE_SERVER_BASE_URL}
            - VITE_SONGS_URL=${VITE_SONGS_URL}
            - VITE_SONG_LYRICS_URL=${VITE_SONG_LYRICS_URL}
            - PORT=5173
        ports:
            - "5173:5173"
    lyrk-stack-backend:
        networks:
            - lyrk-stack-network
        build:
            dockerfile: ./docker/backend/dockerfile
        environment:
            - VITE_SERVER_BASE_URL=${VITE_SERVER_BASE_URL}
        ports:
            - "3001:3001"
        volumes:
            - ./api/songbook.db:/app/api/songbook.db
